### PR TITLE
fix dune dependency constraint

### PR DESCRIPTION
**Pull request by naartjie**

### CODE REVIEW

**Comment by wokalski** [comment]
Why is this needed?

**Comment by wokalski** [comment]
This is quite strange. Where do our requirements come from?

**Review by wokalski — APPROVED** [review]

**Comment by naartjie** [comment]
> This is quite strange. Where do our requirements come from, i.e. the need for 2.9?

@wokalski I bumped it to 2.9 when doing the cram tests. I'm not actually sure if cram requires version 2.9. Since we're on an esy workflow it shouldn't be a problem, or are you thinking of the ability to build stork without esy? Do you want me to check if it works with dune < 2.9?

As for the 2 requirements in opam, both `dune-project` and `dune` specify version 2.9, and maybe that's why the opam file gets generated like that. I'll take a look to see if we can get rid of the duplication.

**Comment by naartjie** [comment]
@wokalski fixed with 509b60b12b71544f9b2bf5154fcb7c0be7b1ddcd

Cram needs dune >= 2.7

**Comment by tsnobip** [comment]
@wokalski @naartjie if we use dune-lang 2.9 in `dune-project` we have to keep dune >= 2.9 I think.

**Pull request merged**
